name: Build and publish SonicDE RPM repo

on:
  workflow_dispatch:
  schedule:
    - cron: "17 */6 * * *"

permissions:
  contents: write
  actions: write
  pages: write
  id-token: write

jobs:
  publish:
    uses: n-a-m-e/linux-package-builder/.github/workflows/publish.yml@main
    with:
      package-type: rpm
      app-id: sonicde
      source-git: https://github.com/n-a-m-e/rpm-app-sonicde.git
      build-script: build.sh
      targets: |
        fedora-44-x86_64
      rebuild-trigger: |
        git sonic-app https://github.com/n-a-m-e/rpm-app-sonicde.git main
